version: '3'

services:
  db:
    image: postgres:16.2-alpine3.19
    ports:
      - '5432:5432'
    env_file:
      - .env

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
