# Generated by Django 5.0.3 on 2024-04-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tags_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todo.tags'),
        ),
    ]
