# Generated by Django 5.0.3 on 2024-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='todo.task'),
        ),
    ]
