# Generated by Django 5.0.3 on 2024-04-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_tag_alter_task_tag_delete_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, to='todo.tag'),
        ),
    ]
